#pragma once

#define IOCTL_ALPC_START_MONITORING CTL_CODE(FILE_DEVICE_UNKNOWN, 0x800, METHOD_BUFFERED, FILE_ANY_ACCESS)
#define IOCTL_ALPC_STOP_MONITORING  CTL_CODE(FILE_DEVICE_UNKNOWN, 0x801, METHOD_BUFFERED, FILE_ANY_ACCESS)
#define IOCTL_ALPC_GET_MESSAGE      CTL_CODE(FILE_DEVICE_UNKNOWN, 0x802, METHOD_BUFFERED, FILE_ANY_ACCESS)
#define IOCTL_ALPC_SET_SSN          CTL_CODE(FILE_DEVICE_UNKNOWN, 0x803, METHOD_BUFFERED, FILE_ANY_ACCESS)
#define IOCTL_ALPC_FIND_RPC_CALLEE  CTL_CODE(FILE_DEVICE_UNKNOWN, 0x804, METHOD_BUFFERED, FILE_ANY_ACCESS)

#define MAX_STACK_FRAMES 32
#define DATA_MAX_LENGTH 2048

typedef struct _ALPC_MONITOR_MESSAGE {
    LARGE_INTEGER Timestamp;
    ULONG PortHandle;
    ULONG ProcessId;
    ULONG ThreadId;
    CHAR ProcessName[16];
    BOOLEAN IsSend;
    ULONG MessageId;
    USHORT MessageType;
    USHORT DataLength;
    USHORT TotalLength;
    UCHAR Data[DATA_MAX_LENGTH];
    ULONG StackFrameCount;
    PVOID StackFrames[MAX_STACK_FRAMES];
} ALPC_MONITOR_MESSAGE, * PALPC_MONITOR_MESSAGE;

#define MAX_MODULE_NAME_LEN 256
#define MAX_IMAGE_NAME_LEN 32

typedef struct _RPC_CALLEE_INFO_REQUEST {
    ULONG ServerProcessId;
    GUID InterfaceUuid;
    UCHAR FunctionId;
} RPC_CALLEE_INFO_REQUEST, * PRPC_CALLEE_INFO_REQUEST;

typedef struct _RPC_CALLEE_INFO_RESPONSE {
    WCHAR ImageName[MAX_IMAGE_NAME_LEN];
    WCHAR ModuleName[MAX_MODULE_NAME_LEN];
    ULONG64 Offset;
    PVOID RawAddress;
} RPC_CALLEE_INFO_RESPONSE, * PRPC_CALLEE_INFO_RESPONSE;

#define SystemModuleInformation 11